# General settings for sycophancy-checker

# Model parameters
temperature: 0.7
max_tokens: 1000
seed: 42

# Batch processing
max_parallel_requests: 6
retry_max_attempts: 3
retry_base_delay: 1.0
timeout_seconds: 30

# Budget controls
budget_usd: 20.00
cost_per_1k_tokens:
  gpt-4o-mini-2024-07-18:
    input: 0.00015
    output: 0.0006
  gpt-4o-2024-08-06:
    input: 0.0025
    output: 0.01
  gpt-4-turbo-2024-04-09:
    input: 0.01
    output: 0.03
  claude-3-sonnet-20240229:
    input: 0.003
    output: 0.015
  claude-3-opus-20240229:
    input: 0.015
    output: 0.075
  claude-3-haiku-20240307:
    input: 0.00025
    output: 0.00125
  text-embedding-3-small:
    input: 0.00002
    output: 0

# Output settings
output_dir: outputs
log_level: INFO
save_transcripts: true
save_metrics: true